bma 2 l 1 commit
bmaayandexru/go_final_project pull request #1
Opened 2024-07-11 19:21 UTC by bmaayandexru

2024-07-31 19:39 UTC, dirtymew requested changes
Привет Михаил

отличная работа 

хочу отметить:
 - документацию
 - docker
 - в целом понятный код
 

дал комментарии что поправить и улучшить - для первой итерации достаточно 

по архитектуре и структуре проекта
 - https://github.com/golang-standards/project-layout
 - https://medium.com/@shershnev/layered-architecture-implementation-in-golang-6318a72c1e10

2024-07-31 19:39 UTC, dirtymew commented on dbt/dbtools.go
> +		fmt.Println("InitDB err:", err)
а смысл дальше работать если нет бд 

я мы вернул ошибку и по месту вызова писал ее в лог и паниковал там

2024-07-31 19:39 UTC, dirtymew commented on dbt/dbtools.go
> +	defer SqlDB.Close()
defer сразу стоит сразу писать после Open

2024-07-31 19:39 UTC, dirtymew commented on dbt/dbtools.go
> +	SqlDB, _ = sql.Open("sqlite", StrDBFile)
это не хорошо - на каждый вызов открывать подключение
они ограничены - стоит один раз при старте инициализировать подлючение и его использовать

посмотри в задании про посылка как там был сделан storage

2024-07-31 19:39 UTC, dirtymew commented on dbt/dbtools.go
> +	row := SqlDB.QueryRow("SELECT * FROM scheduler WHERE id = :id", sql.Named("id", id))
лучше явно указать поля чем *

2024-07-31 19:39 UTC, dirtymew commented on dbt/dbtools.go
> +		sql.Named("limit", 50))
лимит в константу вынести

2024-07-31 19:39 UTC, dirtymew commented on dbt/dbtools.go
> +		sql.Named("date", date.Format("20060102")),
20060102 в константу и везде использовать

2024-07-31 19:39 UTC, dirtymew commented on dbt/dbtools.go
> +func QueryByString(search string) (*sql.Rows, error) {
мб один метод Find или Search(filter string) - вместо кучи методов... 

были бы страндартные CRUD методы

2024-07-31 19:39 UTC, dirtymew commented on dbt/dbtools.go
> +func DeleteByID(id string) (sql.Result, error) {
а зачем sql.Result *sql.Rows И так далее возвращать - верни сразу Task err

2024-07-31 19:39 UTC, dirtymew commented on dbt/nextdate/nextdate.go
> +	template              = "20060102"
мб глобальную константу и везде использовать

2024-07-31 19:39 UTC, dirtymew commented on edb/docker-compose.yml
> +    image: alpine:latest
лучше фиксировать версию всегда

2024-07-31 19:39 UTC, dirtymew commented on edb/docker-compose.yml
> +#    environment:
если лишнее то удаляй

2024-07-31 19:39 UTC, dirtymew commented on main.go
> +		pass := os.Getenv("TODO_PASSWORD")
это не хорошо - делать syscall в запросе 

стоит все переменные при старте приложения прочитать и не делать так

2024-07-31 19:39 UTC, dirtymew commented on dbt/dbtools.go
> +	"github.com/bmaayandexru/go_final_project/tests"
тесты не нужно использовать в коде - это тесты!!

2024-07-31 19:39 UTC, dirtymew commented on tests/addtask_4_test.go
> +		{"", "Заголовок4", "", ""}, //*
тесты не нужно трогать - нужно вернуть как было

2024-07-31 19:39 UTC, dirtymew commented on tests/db_2_test.go
> +		dbfile = "../" + envFile // так чтоб работало с переменной окружения
ну это еще допустимо ...

2024-07-31 19:39 UTC, dirtymew commented on tests/nextdate_3_test.go
> +		{"20240202", "d 30", `20240303`}, //*
тоже отревертить изменения

2024-07-31 19:39 UTC, dirtymew commented on tests/settings.go
> +var Token = "106ca1b823ceb804d7c014a5019632a780f7ce32c7a8737abe41de56f2037c7d"
хмм что-то на jwt не сильно похоже...

2024-07-31 19:39 UTC, dirtymew commented on tests/settings.go
> +var DBFileRun = "scheduler.db"
это нужно убрать отсюда - это конфиг тестов

2024-07-31 19:39 UTC, dirtymew commented on handlers/handlers.go
> +	now, err := time.Parse("20060102", strNow)
используй константу

2024-07-31 19:39 UTC, dirtymew commented on handlers/handlers.go
> +	res.Write(aBytes)
_ , _ = res.Write(aBytes)

тут нужно либо явно проигнорировать ошибку или ее логировать

хорошие линтеры на это ругаться будут и не зря

2024-07-31 19:39 UTC, dirtymew commented on handlers/handlers.go
> +	fmt.Printf("Строка *%s*\n", search)
не стоит каждый запрос логировать - понимаю что это не было в курсе

но стоит или убрать или использовать логеры с разным уровнем логирования

2024-07-31 19:39 UTC, dirtymew commented on handlers/handlers.go
> +	rows, err := dbt.QueryByString(search)
лучше организовать слой storage и возвращать уже понятый task 

так ты уменьшишь связность и будешь работать с понятной структурой Task - 
хендлеры не будут знать о бд

2024-08-01 04:50 UTC, bmaayandexru commented on handlers/handlers.go
> +	now, err := time.Parse("20060102", strNow)
в какой строке? для чего? что обернуть в константу?

2024-08-01 04:54 UTC, bmaayandexru commented on handlers/handlers.go
> +	fmt.Printf("Строка *%s*\n", search)
"использовать логеры с разным уровнем логирования" про это не было. где найти подробности? или рааскажите пожалуйста кратко сами.

2024-08-01 08:05 UTC, dirtymew commented on handlers/handlers.go
> +	now, err := time.Parse("20060102", strNow)
я про 20060102 - много где используется - стоит одну глобальную константу где-то завести и использовать

2024-08-01 08:14 UTC, dirtymew commented on handlers/handlers.go
> +	fmt.Printf("Строка *%s*\n", search)
логирования за рамками данного курсе - поэтому можно не делать,  но писать каждый запрос в лог это не очень хорошо - будет слишком много логов.

поэтому лучше только ошибки логировать

по поводу логеров - это большая тема, есть стандартный пакет log, и куча других типа logrus, zap итд

если логер поддерживает разные уровни легирования типа INFO WARN DEBUG TRACE - то например в можно писать логи уровне debug или trace прям запросы - и стандартном режиме работы приложения они не будут попадать в лог только если включить  debug - это конечно нужно все писать

2024-08-01 13:33 UTC, bmaayandexru commented on dbt/dbtools.go
> +	SqlDB, _ = sql.Open("sqlite", StrDBFile)
А я подумал, что так лучше. База всегда закрыта и в случае чего сохранится. Видимо не правильно подумал. Открою на весь сеанс. Тогда defer Close() не нужно? Как лучше и правильнее?

2024-08-01 13:40 UTC, bmaayandexru commented on dbt/dbtools.go
> +	SqlDB, _ = sql.Open("sqlite", StrDBFile)
В примере с посылками база открывается прямо в main() и если без ошибок тогда и стоит defer Close(). Так делать?

2024-08-01 13:44 UTC, bmaayandexru commented on dbt/dbtools.go
> +	row := SqlDB.QueryRow("SELECT * FROM scheduler WHERE id = :id", sql.Named("id", id))
Не понятно чем лучше. Нужны все поля. Возвращать будем целиком структуру. Можете объяснить чем лучше указывать поля по отдельности чем "*"?

2024-08-01 13:47 UTC, bmaayandexru commented on handlers/handlers.go
> +	fmt.Printf("Строка *%s*\n", search)
принято. а можно закоментить и не убирать совсем?

2024-08-01 13:55 UTC, bmaayandexru commented on handlers/handlers.go
> +	rows, err := dbt.QueryByString(search)
В примере с посылками две прослойки service и storage. Мне тоже две делать? Или достаточно одного storage?

2024-08-01 13:59 UTC, dirtymew commented on dbt/dbtools.go
> +	SqlDB, _ = sql.Open("sqlite", StrDBFile)
можно так - можно если ты сделаешь абстракцию storage то метод Close() у структуры можно определить

2024-08-01 14:03 UTC, dirtymew commented on dbt/dbtools.go
> +	row := SqlDB.QueryRow("SELECT * FROM scheduler WHERE id = :id", sql.Named("id", id))
не лучше если ты управляешь своей бд - а если бд будет внешняя? может поменяться состав полей, может поменяться порядок...

2024-08-01 14:04 UTC, dirtymew commented on handlers/handlers.go
> +	fmt.Printf("Строка *%s*\n", search)
как тебе больше нравиться - я бы убрал

2024-08-01 14:06 UTC, dirtymew commented on handlers/handlers.go
> +	rows, err := dbt.QueryByString(search)
по хорошему сервис тут был бы полезен - например для обработки энпоинта nextdate и taskdone

если сложно то можно одним стораджем обойтись и эту логику на хендлеры повесить - я настаивать не буду

но правильно конечно с service

2024-08-01 14:08 UTC, bmaayandexru commented on tests/settings.go
> +var Token = "106ca1b823ceb804d7c014a5019632a780f7ce32c7a8737abe41de56f2037c7d"
я так понял, что тут может быть что угодно. любой hash. ну и сделал sha256.Sum256()

2024-08-01 14:17 UTC, dirtymew commented on tests/settings.go
> +var Token = "106ca1b823ceb804d7c014a5019632a780f7ce32c7a8737abe41de56f2037c7d"
https://jwt.io в помошь и можно из куки на фронте взять )

это же тесты - стоит использовать что-то похожее на реальные данные...

2024-08-01 14:51 UTC, bmaayandexru commented on dbt/dbtools.go
> +	row := SqlDB.QueryRow("SELECT * FROM scheduler WHERE id = :id", sql.Named("id", id))
теперь понятно. сделаем.

2024-08-01 14:51 UTC, bmaayandexru commented on dbt/dbtools.go
> +		sql.Named("limit", 50))
будет

2024-08-01 14:51 UTC, bmaayandexru commented on tests/settings.go
> +var DBFileRun = "scheduler.db"
ок

2024-08-01 14:51 UTC, bmaayandexru commented on handlers/handlers.go
> +	now, err := time.Parse("20060102", strNow)
ок

2024-08-01 14:52 UTC, bmaayandexru commented on handlers/handlers.go
> +	res.Write(aBytes)
ок

2024-08-01 14:53 UTC, bmaayandexru commented on handlers/handlers.go
> +	rows, err := dbt.QueryByString(search)
значит будет service

2024-08-06 21:50 UTC, bmaayandexru commented on dbt/dbtools.go
> +	defer SqlDB.Close()
это не правил, иначе не работает. база закрывается после выхода из процедуры.

2024-08-06 22:21 UTC, bmaayandexru commented on tests/settings.go
> +var DBFileRun = "scheduler.db"
убрал

2024-08-07 18:09 UTC, dirtymew requested changes
Привет Михаил

дал рекомендации по тому как сервис сделать

в целом готов и так задание засчитать -  если не будешь править , пришли на ревью снова

2024-08-07 18:09 UTC, dirtymew commented on service/service.go
> +func (ts TaskService) Add(task dbt.Task) (sql.Result, error) {
мои рекомендации: 
сервис в - service.go
сторадж - storage.go

интерфейс сервиса
 - add
 - update
 - delete
 - done
 - get
 - find - тут можно и getall или search - что удобнее

интерфейс стораджа
- add/create
- find
- get
- update
- delete

можно интерфейсы описать и разделить по пакетам реализации

2024-08-07 20:12 UTC, bmaayandexru commented on service/service.go
> +func (ts TaskService) Add(task dbt.Task) (sql.Result, error) {
Буду делать. Интересно. Про add/create у стораджа хотелось бы пояснений. Спс. Жду объяснений

2024-08-07 20:20 UTC, bmaayandexru commented on service/service.go
> +func (ts TaskService) Add(task dbt.Task) (sql.Result, error) {
интерфейс сервиса

add добавить одну
update изменить одну
delete удалить одну
done выполнить (изменить или удалить)
get взять одну по id
find - тут можно и getall или search - что удобнее ---- это по строке или дате

интерфейс стораджа

add/create добавить одну
find найти по строке или дате все
get взять по id одну
update изменить одну
delete удалить одну

2024-08-07 20:20 UTC, bmaayandexru commented on service/service.go
> +func (ts TaskService) Add(task dbt.Task) (sql.Result, error) {
так?

2024-08-08 16:55 UTC, dirtymew commented on service/service.go
> +func (ts TaskService) Add(task dbt.Task) (sql.Result, error) {
@bmaayandexru не увидел вопрос в потоке оповещений 

я имел в виду что метод можно назвать Add или Create

2024-08-08 16:59 UTC, dirtymew approved these changes
Привет Михаил

все верно сделал - отлично получилось

задание считаю выполненным

Поздравляю и желаю удачи

2024-08-08 16:59 UTC, dirtymew commented on service/service.go
> +func (ts TaskService) Add(task storage.Task) (sql.Result, error) {
еще можно обявить интерфейс и тут и у строраджа и использовать их для зависимостей

interface Service {
     Add(task storage.Task) (sql.Result, error)
     ....
}

func NewTaskService(store storage.TaskStore) Service {

... но это так для расширяемости и чистоты архитектуры )

2024-08-08 17:06 UTC, merged